// --- Mock Product Data ---
export const products = [
    {
        id: 'prod1',
        name: 'Modern Sofa',
        price: 799.99,
        description: 'A comfortable and stylish modern sofa, perfect for any living room. Upholstered in high-quality fabric.',
        imageUrl: 'https://placehold.co/400x300/F0F0F0/333333?text=Modern+Sofa',
        category: 'Living Room',
        dimensions: '80"W x 35"D x 30"H',
        material: 'Fabric, Wood Frame',
    },
    {
        id: 'prod2',
        name: 'Dining Table Set',
        price: 1200.00,
        description: 'Elegant dining table with four matching chairs, made from solid oak. Ideal for family dinners.',
        imageUrl: 'https://placehold.co/400x300/F0F0F0/333333?text=Dining+Table',
        category: 'Dining Room',
        dimensions: '60"L x 36"W x 30"H',
        material: 'Solid Oak',
    },
    {
        id: 'prod3',
        name: 'Queen Bed Frame',
        price: 550.00,
        description: 'Sturdy and stylish queen-sized bed frame with a minimalist design. Easy to assemble.',
        imageUrl: 'https://placehold.co/400x300/F0F0F0/333333?text=Queen+Bed',
        category: 'Bedroom',
        dimensions: '85"L x 62"W x 45"H',
        material: 'Metal, Wood Slats',
    },
    {
        id: 'prod4',
        name: 'Ergonomic Office Chair',
        price: 299.99,
        description: 'High-back ergonomic office chair with adjustable lumbar support and armrests. Perfect for long work hours.',
        imageUrl: 'https://placehold.co/400x300/F0F0F0/333333?text=Office+Chair',
        category: 'Office',
        dimensions: '26"W x 26"D x 48"H (adjustable)',
        material: 'Mesh, Steel Base',
    },
    {
        id: 'prod5',
        name: 'Bookshelf',
        price: 180.00,
        description: 'Five-tier bookshelf with a contemporary design. Great for organizing books and decor.',
        imageUrl: 'https://placehold.co/400x300/F0F0F0/333333?text=Bookshelf',
        category: 'Living Room',
        dimensions: '30"W x 12"D x 70"H',
        material: 'Engineered Wood',
    },
    {
        id: 'prod6',
        name: 'Coffee Table',
        price: 250.00,
        description: 'Sleek glass top coffee table with a metal frame. Adds a modern touch to your living space.',
        imageUrl: 'https://placehold.co/400x300/F0F0F0/333333?text=Coffee+Table',
        category: 'Living Room',
        dimensions: '40"L x 20"W x 18"H',
        material: 'Tempered Glass, Steel',
    },
];
